//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePageBloggProject_ServerSideVersion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloggPost
    {
        public string slug { get; set; }
        public string title { get; set; }
        public string post { get; set; }
        public string author { get; set; }
        public System.DateTime date { get; set; }
    }
}
